package config

const (
	CFG_IP_PORT              = "IP_PORT"
	CFG_SERVER_READ_TIMEOUT  = "SERVER_READ_TIMEOUT"
	CFG_SERVER_WRITE_TIMEOUT = "SERVER_WRITE_TIMEOUT"
)

const (
	ENV_LOG_PATH        = "LOGGER_PATH"
	ENV_APP_CONFIG_PATH = "APP_CONFIG_PATH"
)
